/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c ConfigurationIfAdaptor -a confifadaptor.h:confifadaptor.cpp -i genivi-dbus-types.h -i ConfigurationImpl.h -l ConfigurationImpl ../genivi-positioning-configuration-qt.xml org.genivi.positioning.Configuration
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CONFIFADAPTOR_H_1381241789
#define CONFIFADAPTOR_H_1381241789

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "genivi-dbus-types.h"
#include "ConfigurationImpl.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.genivi.positioning.Configuration
 */
class ConfigurationIfAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.genivi.positioning.Configuration")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.genivi.positioning.Configuration\">\n"
"    <version>2.0.0 (04-06-2013)</version>\n"
"    <doc>\n"
"      <line>Configuration = This interface allows a client application to set and retrieve configuration options</line>\n"
"    </doc>\n"
"    <method name=\"GetVersion\">\n"
"      <doc>\n"
"        <line>GetVersion = This method returns the API version implemented by the server application.</line>\n"
"      </doc>\n"
"      <annotation value=\"GeniviVersion\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"(qqqs)\" name=\"version\">\n"
"        <doc>\n"
"          <line>version = struct(major,minor,micro,date)</line>\n"
"          <line>major = when the major changes, then backward compatibility with previous releases is not granted</line>\n"
"          <line>minor = when the minor changes, then backward compatibility with previous releases is granted, but something changed in the implementation of the API (e.g. new methods may have been added)</line>\n"
"          <line>micro = when the micro changes, then backward compatibility with previous releases is granted (bug fixes or documentation modifications)</line>\n"
"          <line>date = release date (e.g. 21-06-2011)</line>\n"
"        </doc>\n"
"      </arg>\n"
"    </method>\n"
"    <method name=\"GetProperties\">\n"
"      <doc>\n"
"        <line>GetProperties = This method returns all global system properties.</line>\n"
"      </doc>\n"
"      <annotation value=\"QVariantMap\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{sv}\" name=\"properties\"/>\n"
"    </method>\n"
"    <method name=\"SetProperty\">\n"
"      <doc>\n"
"        <line>SetProperty = This method changes the value of the specified property</line>\n"
"        <line>Only properties that are listed as read-write are changeable</line>\n"
"        <line>On success a PropertyChanged signal will be emitted</line>\n"
"      </doc>\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\">\n"
"        <doc>\n"
"          <line>name = property name</line>\n"
"        </doc>\n"
"      </arg>\n"
"      <arg direction=\"in\" type=\"v\" name=\"value\">\n"
"        <doc>\n"
"          <line>value = property value</line>\n"
"        </doc>\n"
"      </arg>\n"
"      <error name=\"org.genivi.positioning.Configuration.Error.InvalidProperty\"/>\n"
"    </method>\n"
"    <signal name=\"PropertyChanged\">\n"
"      <doc>\n"
"        <line>PropertyChanged = This signal is emitted when a property changes</line>\n"
"      </doc>\n"
"      <arg type=\"s\" name=\"name\">\n"
"        <doc>\n"
"          <line>name = property name</line>\n"
"        </doc>\n"
"      </arg>\n"
"      <arg type=\"v\" name=\"value\">\n"
"        <doc>\n"
"          <line>value = property value</line>\n"
"        </doc>\n"
"      </arg>\n"
"    </signal>\n"
"    <property access=\"readwrite\" type=\"q\" name=\"SatelliteSystem\">\n"
"      <doc>\n"
"        <line>SatelliteSystem = enum(INVALID,GPS,GLONASS,GALILEO,COMPASS, ... )</line>\n"
"      </doc>\n"
"    </property>\n"
"    <property access=\"readwrite\" type=\"i\" name=\"UpdateInterval\">\n"
"      <doc>\n"
"        <line>UpdateInterval = update interval in ms</line>\n"
"      </doc>\n"
"    </property>\n"
"    <method name=\"GetSupportedProperties\">\n"
"      <doc>\n"
"        <line>GetSupportedProperties = This method returns all suppported global system properties</line>\n"
"      </doc>\n"
"      <annotation value=\"MapUShortVariant\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{sv}\" name=\"properties\">\n"
"        <doc>\n"
"          <line>properties = array[property]</line>\n"
"          <line>property = dictionary[key,value]</line>\n"
"          <line>key = enum(SatelliteSystem,UpdateInterval, ... )</line>\n"
"          <line>key = SatelliteSystem, value = value of type 'aq'; 'q' is an enum(INVALID,GPS,GLONASS,GALILEO,COMPASS, ...)</line>\n"
"          <line>key = UpdateInterval, value = value of type 'ai'; 'i' is the update interval in ms</line>\n"
"        </doc>\n"
"      </arg>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ConfigurationIfAdaptor(ConfigurationImpl *parent);
    virtual ~ConfigurationIfAdaptor();

    inline ConfigurationImpl *parent() const
    { return static_cast<ConfigurationImpl *>(QObject::parent()); }

public: // PROPERTIES
    Q_PROPERTY(ushort SatelliteSystem READ satelliteSystem WRITE setSatelliteSystem)
    ushort satelliteSystem() const;
    void setSatelliteSystem(ushort value);

    Q_PROPERTY(int UpdateInterval READ updateInterval WRITE setUpdateInterval)
    int updateInterval() const;
    void setUpdateInterval(int value);

public Q_SLOTS: // METHODS
    QVariantMap GetProperties();
    MapUShortVariant GetSupportedProperties();
    GeniviVersion GetVersion();
    void SetProperty(const QString &name, const QDBusVariant &value);
Q_SIGNALS: // SIGNALS
    void PropertyChanged(const QString &name, const QDBusVariant &value);
};

#endif
