/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c AgentAdaptor -a agentadaptor.h:agentadaptor.cpp -i genivi-dbus-types.h -i agentimpl.h -l AgentImpl ../EnhancedPositionAgent.xml org.genivi.position.EnhancedPositionAgent
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef AGENTADAPTOR_H_1320934380
#define AGENTADAPTOR_H_1320934380

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "genivi-dbus-types.h"
#include "agentimpl.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.genivi.position.EnhancedPositionAgent
 */
class AgentAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.genivi.position.EnhancedPositionAgent")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.genivi.position.EnhancedPositionAgent\">\n"
"    <version>0.0.5</version>\n"
"    <doc/>\n"
"    <!--	 \n"
"	<method name=\"CourseUpdate\">\n"
"	<doc>\n"
"	<line>is called when the course changed</line>\n"
"	</doc>\n"
"		<arg name=\"validFields\" type=\"b\" direction=\"in\" >\n"
"		<doc>\n"
"		<line>validFields = bit mask indicating which fields contain valid information</line>\n"
"		</doc>\n"
"		</arg>\n"
"		<arg name=\"heading\" type=\"d\" direction=\"in\" >\n"
"		<doc>\n"
"		<line>todo</line>\n"
"		</doc>\n"
"		</arg>\n"
"		<arg name=\"speed\" type=\"d\" direction=\"in\" >\n"
"		<doc>\n"
"		<line>todo</line>\n"
"		</doc>\n"
"		</arg>\n"
"		<arg name=\"climb\" type=\"d\" direction=\"in\" >\n"
"		<doc>\n"
"		<line>todo</line>\n"
"		</doc>\n"
"		</arg>\n"
"		<arg name=\"yawRate\" type=\"d\" direction=\"in\" >\n"
"		<doc>\n"
"		<line>todo</line>\n"
"		</doc>\n"
"		</arg>\n"
"		<arg name=\"timestamp\" type=\"u\" direction=\"in\" >\n"
"		<doc>\n"
"		<line>timestamp in [ms]</line>\n"
"		</doc>\n"
"		</arg>\n"
"	</method>\n"
"-->\n"
"    <method name=\"StatusUpdate\">\n"
"      <doc>\n"
"        <line>This method is called if the status changed.</line>\n"
"      </doc>\n"
"      <arg direction=\"in\" type=\"u\" name=\"status\">\n"
"        <doc>\n"
"          <line>status = enum(INVALID(0x00),UNKNOWN(0x01),DISCONNECTED(0x02),STARTUP(0x03),READY(0x04),CONNECTED(0x05) ... )</line>\n"
"        </doc>\n"
"      </arg>\n"
"    </method>\n"
"    <method name=\"PositionUpdate\">\n"
"      <doc>\n"
"        <line>This method is called if the position changed.</line>\n"
"      </doc>\n"
"      <arg direction=\"in\" type=\"a(b)\" name=\"validFields\">\n"
"        <annotation value=\"QList&lt;bool>\" name=\"com.trolltech.QtDBus.QtTypeName.In0\"/>\n"
"        <doc>\n"
"          <line>bit mask indicating which fields contain valid information</line>\n"
"        </doc>\n"
"      </arg>\n"
"      <arg direction=\"in\" type=\"d\" name=\"latitude\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"longitude\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"altitude\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"timestamp\">\n"
"        <doc>\n"
"          <line>timestamp in [ms]</line>\n"
"        </doc>\n"
"      </arg>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    AgentAdaptor(AgentImpl *parent);
    virtual ~AgentAdaptor();

    inline AgentImpl *parent() const
    { return static_cast<AgentImpl *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void PositionUpdate(const QList<bool> &validFields, double latitude, double longitude, double altitude, uint timestamp);
    void StatusUpdate(uint status);
Q_SIGNALS: // SIGNALS
};

#endif
