/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c AgentAdaptor -a agentadaptor.h:agentadaptor.cpp -i genivi-dbus-types.h -i agentimpl.h -l AgentImpl ../EnhancedPositionAgent.xml org.genivi.position.EnhancedPositionAgent
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "agentadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AgentAdaptor
 */

AgentAdaptor::AgentAdaptor(AgentImpl *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AgentAdaptor::~AgentAdaptor()
{
    // destructor
}

void AgentAdaptor::PositionUpdate(const QList<bool> &validFields, double latitude, double longitude, double altitude, uint timestamp)
{
    // handle method call org.genivi.position.EnhancedPositionAgent.PositionUpdate
    parent()->PositionUpdate(validFields, latitude, longitude, altitude, timestamp);
}

void AgentAdaptor::StatusUpdate(uint status)
{
    // handle method call org.genivi.position.EnhancedPositionAgent.StatusUpdate
    parent()->StatusUpdate(status);
}

