/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c DemoIfAdaptor -a demoifadaptor.h:demoifadaptor.cpp -i genivi-dbus-types.h -i serverimpl.h -l ServerImpl ../genivi-positioning-enhancedposition-qt.xml org.genivi.positioning.EnhancedPosition
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "demoifadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DemoIfAdaptor
 */

DemoIfAdaptor::DemoIfAdaptor(ServerImpl *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DemoIfAdaptor::~DemoIfAdaptor()
{
    // destructor
}

MapUShortVariant DemoIfAdaptor::GetAccuracy()
{
    // handle method call org.genivi.positioning.EnhancedPosition.GetAccuracy
    return parent()->GetAccuracy();
}

MapUShortVariant DemoIfAdaptor::GetData(const QList<ushort> &valuesToReturn)
{
    // handle method call org.genivi.positioning.EnhancedPosition.GetData
    return parent()->GetData(valuesToReturn);
}

MapUShortVariant DemoIfAdaptor::GetPosition()
{
    // handle method call org.genivi.positioning.EnhancedPosition.GetPosition
    return parent()->GetPosition();
}

MapUShortVariant DemoIfAdaptor::GetRotationRate()
{
    // handle method call org.genivi.positioning.EnhancedPosition.GetRotationRate
    return parent()->GetRotationRate();
}

MapUShortVariant DemoIfAdaptor::GetSatelliteInfo()
{
    // handle method call org.genivi.positioning.EnhancedPosition.GetSatelliteInfo
    return parent()->GetSatelliteInfo();
}

MapUShortVariant DemoIfAdaptor::GetStatus()
{
    // handle method call org.genivi.positioning.EnhancedPosition.GetStatus
    return parent()->GetStatus();
}

MapUShortVariant DemoIfAdaptor::GetTime()
{
    // handle method call org.genivi.positioning.EnhancedPosition.GetTime
    return parent()->GetTime();
}

GeniviVersion DemoIfAdaptor::GetVersion()
{
    // handle method call org.genivi.positioning.EnhancedPosition.GetVersion
    return parent()->GetVersion();
}

